import React from 'react'
import { AiOutlineEye, AiOutlineHeart } from 'react-icons/ai'
import { BsBarChartLine } from 'react-icons/bs'

export const Data = [
  {
    id: 1,
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/products/p1.jpg',
    title: 'add to card',
    icon_0: <AiOutlineEye />,
    icon_1: <AiOutlineHeart />,
    icon_2: <BsBarChartLine />,
    title_2: 'women hot collection',
    price: 29.0,
    linkIcnos: 'quick shop',
  },
  {
    id: 2,
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/products/p3.jpg',
    title: 'add to card',
    icon_0: <AiOutlineEye />,
    icon_1: <AiOutlineHeart />,
    icon_2: <BsBarChartLine />,
    title_2: 'Awesome Pink Show',
    price: 29.0,
    linkIcnos: 'quick shop',
  },
  {
    id: 3,
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/products/p5.jpg',
    title: 'add to card',
    icon_0: <AiOutlineEye />,
    icon_1: <AiOutlineHeart />,
    icon_2: <BsBarChartLine />,
    title_2: 'Awesome bags collection',
    price: 29.0,
    linkIcnos: 'quick shop',
  },
  {
    id: 4,
    img: 'https://wpthemesgrid.com/themes/free/eshop/images/products/p7.jpg',
    title: 'add to card',
    icon_0: <AiOutlineEye />,
    icon_1: <AiOutlineHeart />,
    icon_2: <BsBarChartLine />,
    title_2: 'women pant collection',
    price: 29.0,
    linkIcnos: 'quick shop',
  },
  {
    id: 5,
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/products/p9.jpg',
    title: 'add to card',
    icon_0: <AiOutlineEye />,
    icon_1: <AiOutlineHeart />,
    icon_2: <BsBarChartLine />,
    title_2: 'Awesome bags collection',
    price: 29.0,
    linkIcnos: 'quick shop',
  },
  {
    id: 6,
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/products/p11.jpg',
    title: 'add to card',
    icon_0: <AiOutlineEye />,
    icon_1: <AiOutlineHeart />,
    icon_2: <BsBarChartLine />,
    title_2: 'Awesome cap for women ',
    price: 29.0,
    linkIcnos: 'quick shop',
  },
  {
    id: 7,
    img: '		https://wpthemesgrid.com/themes/free/eshop/images/products/p13.jpg',
    title: 'add to card',
    icon_0: <AiOutlineEye />,
    icon_1: <AiOutlineHeart />,
    icon_2: <BsBarChartLine />,
    title_2: 'polo dress for women ',
    price: 29.0,
    linkIcnos: 'quick shop',
  },
  {
    id: 8,
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/products/p15.jpg',
    title: 'add to card',
    icon_0: <AiOutlineEye />,
    icon_1: <AiOutlineHeart />,
    icon_2: <BsBarChartLine />,
    title_2: 'Awesome cap for women ',
    price: 50.0,
    linkIcnos: 'quick shop',
  },
]
