import React from 'react'
import { FaShoppingBag } from 'react-icons/fa'
export const Data = [
  // {
  //   title: 'on sale',
  //   title: 'Best Seller',
  //   title: 'Top Viewed',
  // },
  {
    id: 1,
    title: 'on sale',
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list1.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 59,
    id: 2,
    img: '		https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list2.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 44,
    id: 3,
    title: 'on sale',
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list3.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 89,
  },
  {
    id: 4,
    img: '		https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list4.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 65,

    id: 5,
    img: 'https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list5.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 33,
    id: 6,
    img: 'https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list6.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 77,
  },
  {
    id: 7,
    img: '	https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list7.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 22,
    id: 8,
    img: 'https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list8.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 35,
  },
  {
    id: 9,
    img: 'https://wpthemesgrid.com/themes/free/eshop/images/list/shop-list9.jpg',
    icon: <FaShoppingBag />,
    des: 'Licity jelly leg flat Sandals',
    price: 99,
  },
]
